services:
  - type: web
    name: dental-clinic
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=1 --threads=4
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0